# yamllint disable rule:line-length
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observiq-otel-collector
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: observiq-otel-collector
    stack: observiq
  name: observiq-otel-collector
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: observiq-otel-collector
    stack: observiq
  name: observiq-otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observiq-otel-collector
subjects:
  - kind: ServiceAccount
    name: observiq-otel-collector
    namespace: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observiq-otel-collector
  labels:
    app: observiq-otel-collector
    stack: observiq
data:
  collector.yaml: |
    receivers:
      plugin/container:
        path: /etc/otel/plugins/container_logs.yaml
        parameters:
          exclude_file_log_path:
            - /var/log/containers/observiq-*

    processors:
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        pod_association:
        - from: resource_attribute
          name: k8s.pod.uid
        - from: resource_attribute
          name: k8s.pod.name
        filter:
            node_from_env_var: ${KUBE_NODE_NAME}

      batch:
        send_batch_max_size: 200
        send_batch_size: 200

    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true

      logging:

    extensions:
      file_storage:
        directory: /var/lib/observiq/otelcol/node

    service:
      extensions:
        - file_storage
      pipelines:
        logs:
          receivers:
            - plugin/container
          processors:
            - k8sattributes
            - batch
          exporters:
            - otlp
            - logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: observiq-otel-collector
  labels:
    app: observiq-otel-collector
    stack: observiq
spec:
  selector:
    matchLabels:
      app: observiq-otel-collector
      stack: observiq
  template:
    metadata:
      labels:
        app: observiq-otel-collector
        stack: observiq
    spec:
      containers:
        - args:
            - --config=/conf/collector.yaml
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: observiq/observiq-otel-collector:1.9.0
          imagePullPolicy: IfNotPresent
          name: otc-container
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 500Mi
          volumeMounts:
            - mountPath: /conf
              name: otc-internal
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockerlogs
            - mountPath: /var/lib/observiq/otelcol/node
              name: storage
      dnsPolicy: ClusterFirstWithHostNet
      # Required for k8sattributes processor
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        # Must be able to mount host volume and read logs
        # from filesystem and journald.
        runAsUser: 0
      serviceAccount: observiq-otel-collector
      serviceAccountName: observiq-otel-collector
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: collector.yaml
                path: collector.yaml
            name: observiq-otel-collector
          name: otc-internal
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: dockerlogs
        - hostPath:
            path: /var/lib/observiq/otelcol/node
            type: ""
          name: storage
