---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - ../../base/exporters/logging
patchesStrategicMerge:
  - agent_cluster.yaml
  - agent_node.yaml
  - agent_redis.yaml
