---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-sidecar
data:
  config.yaml: |
    receivers:
      statsd:
        endpoint: 127.0.0.1:8125
        aggregation_interval: 60s

    processors:
      resource:
        attributes:
        - key: k8s.namespace.name
          value: "${OTEL_RESOURCE_ATTRIBUTES_NAMESPACE}"
          action: upsert
        - key: k8s.pod.name
          value: "${OTEL_RESOURCE_ATTRIBUTES_POD_NAME}"
          action: upsert

    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true
      logging:

    service:
      pipelines:
        metrics:
          receivers:
            - statsd
          processors:
            - resource
          exporters:
            - otlp
            - logging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-sidecar
spec:
  selector:
    matchLabels:
      app: statsd-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: statsd-sidecar
    spec:
      containers:
        - name: statsd-sidecar
          image: ghcr.io/jsirianni/go-statsd-example:0.0.5
          imagePullPolicy: Always
          resources:
            limits:
              memory: "50Mi"
              cpu: 50m
            requests:
              memory: "50Mi"
          env:
            - name: STATSD_APP_NAME
              value: frontend
            - name: STATSD_HOST
              value: localhost
            - name: OTEL_INCLUDE_RESOURCES
              value: "false"
        - name: otc-container
          image: observiq/observiq-otel-collector:1.11.1
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/otel/config.yaml
              subPath: config.yaml
              name: statsd-sidecar
      volumes:
        - name: statsd-sidecar
          configMap:
            name: statsd-sidecar
            items:
              - key: config.yaml
                path: config.yaml
