# yamllint disable rule:line-length
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: observiq-otel-collector
  namespace: observiq
  labels:
    app: observiq-otel-collector
spec:
  selector:
    matchLabels:
      app: observiq-otel-collector
  template:
    metadata:
      labels:
        app: observiq-otel-collector
    spec:
      containers:
        - args:
            - --config=/conf/collector.yaml
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /otel/credentials.json
            - name: K8S_CLUSTER
              value: minishift
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: observiq/observiq-otel-collector:1.9.2
          imagePullPolicy: IfNotPresent
          name: otc-container
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - mountPath: /conf
              name: otc-internal
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: dockerlogs
            - mountPath: /var/lib/observiq/otelcol/node
              name: storage
            - mountPath: /otel
              name: gcp-credentials
      dnsPolicy: ClusterFirstWithHostNet
      # Required for k8sattributes processor
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        # Must be able to mount host volume and read logs
        # from filesystem and journald.
        runAsUser: 0
      serviceAccount: observiq-otel-collector
      serviceAccountName: observiq-otel-collector
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: collector.yaml
                path: collector.yaml
            name: observiq-otel-collector
          name: otc-internal
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: dockerlogs
        - hostPath:
            path: /var/lib/observiq/otelcol/node
            type: ""
          name: storage
        - name: gcp-credentials
          secret:
            defaultMode: 420
            secretName: gcp-credentials
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
